In [1]:
!pip install caas-jupyter-tools

ERROR: Could not find a version that satisfies the requirement caas-jupyter-tools (from versions: none)
ERROR: No matching distribution found for caas-jupyter-tools

In [3]:
# Convert the uploaded JSON exercises into a CSV suitable for Supabase import
import json, pandas as pd, os

src_json = "exercises_geometry_seed.json"
dst_csv = "exercises_geometry_seed.csv"

# Load JSON
with open(src_json, "r", encoding="utf-8") as f:
    data = json.load(f)

# Keep only the columns that exist on the Supabase table
rows = [
    {
        "title": item.get("title", ""),
        "question_text": item.get("question_text", ""),
        "answer": item.get("answer", ""),
        "difficulty": item.get("difficulty", ""),
    }
    for item in data
]

df = pd.DataFrame(rows, columns=["title", "question_text", "answer", "difficulty"])

# Save to CSV without index

In [4]:
df

,title,question_text,answer,difficulty
0,Area of a Triangle,Sebuah segitiga memiliki alas 12 cm dan tinggi...,72,easy
1,Volume of a Cube,Sebuah kubus memiliki panjang sisi 7 cm. Berap...,343,easy
2,Pythagorean Missing Leg,Sebuah segitiga siku-siku memiliki sisi alas 4...,20,medium
3,Volume of a Cone,Sebuah kerucut memiliki jari-jari 21 cm dan ti...,8316,hard
4,Area of a Rectangle,Sebuah persegi panjang memiliki panjang 10 cm ...,180,easy
...,...,...,...,...
95,Pythagorean Missing Leg,Sebuah segitiga siku-siku memiliki sisi tegak ...,60,medium
96,Volume of a Sphere,Sebuah bola memiliki jari-jari 42 cm. Gunakan ...,310464,hard
97,Surface Area of a Cube,Sebuah kubus memiliki panjang sisi 11 cm. Bera...,726,easy
98,Volume of a Cone,Sebuah kerucut memiliki jari-jari 21 cm dan ti...,4158,hard
99,Volume of a Cone,Sebuah kerucut memiliki jari-jari 14 cm dan ti...,1232,hard

In [5]:
df.to_csv(dst_csv, index=False)